### ISSUE TITLE
discussion: Should we keep envd login subcommand?

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1251]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by xieydd** [comment]
Can you give more information about the discussion? @gaocegege

**Comment by gaocegege** [comment]
We will need `envd login` to login (and register) in the envd server. Then you can create the environments on envd-server.

But we can also create such a user when users run `envd context create`.

This issue is to discuss which one is better.

**Comment by VoVAllen** [comment]
I still think `envd login` won't affect the core user journey. It will only need to be executed once. And user can disable auth at the server side

**Comment by kemingy** [comment]
I think we are talking about several things together.

1. Shall we provide a way for users that do not want to log in with a username & password? (mainly because there is only one user or it's not necessary for them)
2. Shall we help users to log in when they create the context?

---
1. Yes, and I think it should be configured on the envd-server side to allow anonymous users (but we should generate a token when creating the context to identify the user, the name can be a random string)
2. No. I agree with https://github.com/tensorchord/envd/issues/1251#issuecomment-1336952859.

**Comment by VoVAllen** [comment]
> Shall we provide a way for users that do not want to log in with a username & password? (mainly because there is only one user or it's not necessary for them)

I think so. So @gaocegege already has no-auth mode in JWT pr, which won't check the user's password when `envd login`. (any username/password works)

**Comment by xieydd** [comment]
> I think we are talking about several things together.
> 
> 1. Shall we provide a way for users that do not want to log in with a username & password? (mainly because there is only one user or it's not necessary for them)
> 2. Shall we help users to log in when they create the context?
> 
1. no-auth mode supported for anonymous users and auth mode for registed user lgtm.
2. I aggre with allen`s reason,my [comment](https://github.com/tensorchord/envd/issues/1251#issuecomment-1336157036) can be ignored.

**Comment by gaocegege** [comment]
> Shall we provide a way for users that do not want to log in with a username & password? (mainly because there is only one user or it's not necessary for them)

We already support this in the auth PR in envd-server.

**Comment by aseaday** [comment]
I think `envd login` we should keep this command. But the interactive process of envd login shoule be considerated seriously.
