### ISSUE TITLE
feat(bootstrap): Support resume

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1407]
## Description

The bootstrap fails if the envd_buildkitd container is exited. We need to figure out how to resume it, or recreate it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Electronic-Waste** [comment]
Maybe I can have a try!

**Comment by gaocegege** [comment]
Thanks!

**Comment by Electronic-Waste** [comment]
Maybe I need some help when addressing the problem, because I'm not so familiar with the source code.

Also, I noticed that envd does not have a command like `envd shutdown` to kill the envd_buildkitd container so far. Maybe we can add a command like `envd shutdown` , which allows users closing envd as they want, keeping the development environment tidy and neat.

**Comment by gaocegege** [comment]
This issue specifically addresses the problem with the `envd bootstrap` command, which occasionally fails when the `envd_buildkitd` encounters issues, resulting in unsuccessful execution of the command.

**Comment by Electronic-Waste** [comment]
Okay, I see. I've reproduced this scenario by applying `docker pause` to end_buildkitd container.

**Comment by Electronic-Waste** [comment]
> Also, I noticed that envd does not have a command like envd shutdown to kill the envd_buildkitd container so far. Maybe we can add a command like envd shutdown , which allows users closing envd as they want, keeping the development environment tidy and neat.

Maybe I should raise another issue to discuss about it.

**Comment by Electronic-Waste** [comment]
The PR is merged. Thanks!

**Comment by kemingy** [comment]
close due to #1828
