### ISSUE TITLE
bug(pip): subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#409]
We got this issue when:

- running on Lima VM https://github.com/tensorchord/envd/issues/370#issuecomment-1158311464
- running on low-version Docker daemon. https://github.com/tensorchord/envd/issues/340#issuecomment-1156363333

**Comment by gaocegege** [comment]
It can be fixed by:

- run on 20.10.x docker (docker desktop for mac)

**Comment by aseaday** [comment]
It is a cross multi arch problem I had met before. 
FYI
https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-1-the-basics-2fa97869a99b?gi=95b158eb9975

I think we could close this issue.

**Comment by gaocegege** [comment]
@aseaday I think we should support different arches and os (e.g. macOS arch64, Linux arch64) Thus maybe we should keep it open?

**Comment by aseaday** [comment]
The error from this issue's title cames from build amd64 container from arm64 host which could be called build cross (buildx). It would cause lsb_release error because of lsb_release call something from kernel or kernel in vm. 
I think this case is some bug related to docker directly than envd.  The links I mention above is enough for users discovery themselves and in most cases, they could fix it by upgrade their docker client for arm mac.
As for cross arch or multi arch support problem, we'd better open another issue.

**Comment by gaocegege** [comment]
Thanks for the explanation!

SGTM. Then I think we can close it.
