### ISSUE TITLE
feat(CLI): Support run with existing image

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#553]
## Description

`envd up` builds and runs the image by default. But users may not want to build the image from scratch. They may want to use the existing image instead.

We should support it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
Does `use the existing image` means that `envd up` should use the image the user built before?

**Comment by gaocegege** [comment]
Yep.

Maybe `envd run --image <existed-image>`

**Comment by aseaday** [comment]
> Yep.
> 
> Maybe `envd run --image <existed-image>`

Let me gice some specific user scenarios:
1. A user exec `envd up` twice in a same directory, should `envd` rebuild the image or use the image created before.  If all the build config didn't change,  it seems a little wired to `envd up` a new env and less uesful. So we should only care about the situations someone change the build config like updating the env where a user may  import a new package or add some shared data.  `envd up` works like a `envd env update cwd`. 
2. A user copy the current directory into another place for multiple exp debugging.  In that case ,  `envd up` should use the built image for speed.
3. Only if user want to use a custome image rather than envd build config file, there is a way like envd envs create --from-image=<existed-image>

WDYT @gaocegege

**Comment by gaocegege** [comment]
The motivation of the issue is to resolve the first use case: `A user exec envd up twice in a same directory`

Maybe we should add the logic to check if the build manifest `build.envd` changes, to determine if we should rebuild it.

**Comment by aseaday** [comment]
> The motivation of the issue is to resolve the first use case: `A user exec envd up twice in a same directory`
> 
> Maybe we should add the logic to check if the build manifest `build.envd` changes, to determine if we should rebuild it.

Nice, I will introduce the `build.envd` changed and rebuilt first.  Keep 2 and 3 for later use.
When we finished the syntax `load` ,  support for deps update at that time.

**Comment by aseaday** [comment]
A flag: finish it this weekend.

**Comment by aseaday** [comment]
Because we have implement the build or up from existing image. And https://github.com/tensorchord/envd/commit/9b3fbe3c9c91c167196be3764de4f53b1a074489 had achieve the the third item in https://github.com/tensorchord/envd/issues/553#issuecomment-1177106676. 
I think the following job is to improve the mapping between the manifest and image. Hash (Maybe merkle) the manifest's AST and give a label: `asthash=ffff`.  Considering it is only a improvement feature, I decided to cancel `[priority/1-high 🔥](https://github.com/tensorchord/envd/labels/priority%2F1-high%20%F0%9F%94%A5)`.

**Comment by gaocegege** [comment]
SGTM
