### ISSUE TITLE
bug(release): Insufficient permissions to update the homebrew repository

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#908]
## Description

https://github.com/tensorchord/envd/actions/runs/3068539356/jobs/4956126877

We cannot update the homebrew repository in envd's github action. The attack surface will be larger if we use a personal token to push.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Triple-Z** [comment]
You can create an organization-scoped GitHub App, set targeted repos' read/write permission to this GH App , and generate App token which can be used in your `goreleaser`.

FYI: https://micahjon.com/2021/repo-scoped-access-token-for-github-org/

I have solved it for `double-entry-generator` in this PR: https://github.com/deb-sig/double-entry-generator/pull/64

However, I can't help you to create such a GitHub App for this organization because my account lacks on necessary permissions :) You can do it by yourself 🎉

**Comment by gaocegege** [comment]
Thanks for the advice!

**Comment by kemingy** [comment]
Are we able to do this with fine-grained personal access tokens? @gaocegege 

Ref: https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/

**Comment by gaocegege** [comment]
Yep, I already added a new secret.

**Comment by gaocegege** [comment]
I am closing this since we already checked in the homebrew.
